Improved checking of environment variables
My initial implementation was messing up the output of these
scripts. This is not fixed.

diff --git a/bin/boogie b/bin/boogie
--- a/bin/boogie
+++ b/bin/boogie
@@ -1,3 +1,6 @@
 #!/bin/bash
-"${BOOGIE:?The required BOOGIE environment variable is not set. See SMACK documentation for details.}"
+if [ -z "$BOOGIE" ] ; then
+  echo "The required BOOGIE environment variable is not set. See SMACK documentation for details."
+  exit 1
+fi
 $BOOGIE "$@"
diff --git a/bin/corral b/bin/corral
--- a/bin/corral
+++ b/bin/corral
@@ -1,3 +1,6 @@
 #!/bin/bash
-"${CORRAL:?The required CORRAL environment variable is not set. See SMACK documentation for details.}"
+if [ -z "$CORRAL" ] ; then
+  echo "The required CORRAL environment variable is not set. See SMACK documentation for details."
+  exit 1
+fi
 $CORRAL "$@"
diff --git a/bin/lockpwn b/bin/lockpwn
--- a/bin/lockpwn
+++ b/bin/lockpwn
@@ -1,3 +1,6 @@
 #!/bin/bash
-"${LOCKPWN:?The required LOCKPWN environment variable is not set. See SMACK documentation for details.}"
+if [ -z "$LOCKPWN" ] ; then
+  echo "The required LOCKPWN environment variable is not set. See SMACK documentation for details."
+  exit 1
+fi
 $LOCKPWN "$@"
